### ISSUE TITLE
Wrong contentLength calculation on Multipart request

### ISSUE THREAD

**Issue by d-rivals-mazedia** [jblough/TinCanDart#5]
Hi, first of all thank you for this excellent work !
I encouter a case with the use of the attachments coupled with the presence of non ASCII characters in the statement fields : the contentLength calculation omit to UTF8 encode the body before getting his length, which give a different length than the one actually sent.
Precisely the HTTP client fails to send the request with the error : "Content size exceeds specified contentLength."

Is there any chance you can watch this case?
Thanks

**Comment by jblough** [comment]
I can take a look.

**Comment by d-rivals-mazedia** [comment]
Hi @jblough, is it still possible that you can look at this case ?
Thanks a lot

**Comment by jblough** [comment]
It's on my list to look at but unfortunately I haven't had a chance yet.  When it comes to attachments, the behavior can be different based on which LRS is being used.  Which LRS are you using in this situation?  Thanks!

**Comment by d-rivals-mazedia** [comment]
Thank you for your answer, my implementation is based on Learning Locker

**Comment by jblough** [comment]
It looks like it might fix it to change the line at https://github.com/jblough/TinCanDart/blob/master/lib/src/multipart_mixed_request.dart#L56 to 
```length += utf8.encode(_body!).length + newLineLength;```
 but I need to run through some more tests to verify that everything else still works as expected.

**Comment by jblough** [comment]
This should be fixed in the 2.1.0 release

**Comment by d-rivals-mazedia** [comment]
Hi @jblough I can confirm that this solves the problem, thanks !
Although unfortunately I can no longer use it in my target project due to the upgrade of dependencies

**Comment by jblough** [comment]
I've released version 2.1.1 with a reduced minimum Dart SDK version.

**Comment by d-rivals-mazedia** [comment]
That's very nice of you, thanks a lot !
