### ISSUE TITLE
Error to tranform a Statement Json to Statement object

### ISSUE THREAD

**Issue by AndresCidInst** [jblough/TinCanDart#8]
![image](https://github.com/jblough/TinCanDart/assets/121510315/0b13ad85-c613-4722-bf91-ae2f4c917367)

I tried to transform a Statement from a Json, but it broke when transforming the ActivityDefinition to the library's ActivityDefinition object :(

**Comment by jblough** [comment]
Thank you for the bug report!  It looks like I didn't research what the structure of `choices` would be well enough.  It looks like https://adlnet.github.io/xapi-lab/ gives me some sample data to try to get this fixed.

**Comment by jblough** [comment]
This is should be fixed in the 2.1.3 release
